from enum import StrEnum


class AccountStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    RECOVERY_EMAIL_REQUIRED = "RECOVERY_EMAIL_REQUIRED"
    TOTP_SECRET_REQUIRED = "TOTP_SECRET_REQUIRED"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
    CAPTCHA_REQUIRED = "CAPTCHA_REQUIRED"
    PHONE_VERIFICATION_REQUIRED = "PHONE_VERIFICATION_REQUIRED"
    BANNED = "BANNED"
    GOOD = "GOOD"

    def __str__(self):
        return self.value
