import enum


# class DiscordGuildJoinStatus(enum.StrEnum):
#     JOINED = 'JOINED'
#     REQUIRE_CAPTCHA = 'REQUIRE_CAPTCHA'
#     SERVERS_LIMIT_REACHED = 'SERVERS_LIMIT_REACHED'


class RequiredAction(enum.StrEnum):
    AGREEMENTS = 'AGREEMENTS'
    TOS_UPDATE_ACKNOWLEDGMENT = 'TOS_UPDATE_ACKNOWLEDGMENT'
    REQUIRE_CAPTCHA = 'REQUIRE_CAPTCHA'
    REQUIRE_VERIFIED_EMAIL = 'REQUIRE_VERIFIED_EMAIL'
    REQUIRE_REVERIFIED_EMAIL = 'REQUIRE_REVERIFIED_EMAIL'
    REQUIRE_VERIFIED_PHONE = 'REQUIRE_VERIFIED_PHONE'
    REQUIRE_REVERIFIED_PHONE = 'REQUIRE_REVERIFIED_PHONE'
    REQUIRE_REVERIFIED_EMAIL_OR_VERIFIED_PHONE = 'REQUIRE_REVERIFIED_EMAIL_OR_VERIFIED_PHONE'
    REQUIRE_VERIFIED_EMAIL_OR_REVERIFIED_PHONE = 'REQUIRE_VERIFIED_EMAIL_OR_REVERIFIED_PHONE'
    REQUIRE_REVERIFIED_EMAIL_OR_REVERIFIED_PHONE = 'REQUIRE_REVERIFIED_EMAIL_OR_REVERIFIED_PHONE'

    def __str__(self):
        return self.value


class AccountStatus(enum.StrEnum):
    UNKNOWN   = "UNKNOWN"
    BAD_TOKEN = "BAD_TOKEN"
    GOOD      = "GOOD"

    def __str__(self):
        return self.value
