[LOGGING]
LEVEL = "INFO"

[MINT]
DEFAULT_INVITE_CODE = "304799BB"

[TWITTER]
UNLOCK_ATTEMPTS = 5
USE_SUSPENDED_ACCOUNTS = false

[CAPTCHA]
CAPSOLVER_API_KEY = ""

[TRANSACTION]
WAIT_FOR_TX_RECEIPT = false

[CONCURRENCY]
MAX_TASKS = 1
MAX_RETRIES = 3
DELAY_BETWEEN_ACCOUNTS = [0, 0]
DELAY_BETWEEN_ACTIONS = [0, 0]
