[LOGGING]
LEVEL = "INFO"

[CONCURRENCY]
MAX_TASKS = 1
MAX_RETRIES = 3
DELAY_BETWEEN_RETRIES = 5  # sec.
#DELAY_BETWEEN_ACTIONS = [0, 0]  # [min sec., max sec.]
DELAY_BETWEEN_ACCOUNTS = [60, 90]  # [min sec., max sec.]

[REQUESTS]
TIMEOUT = 10  # sec.

[TWITTER]
AUTO_RELOGIN = true
MAX_UNLOCK_ATTEMPTS = 5
USE_SUSPENDED_ACCOUNTS = false

[CAPTCHA]
CAPSOLVER_API_KEY = ""

[TRANSACTION]
WAIT_FOR_TX_RECEIPT = false

# ---< IGNORE IT >---

#[PLAYWRIGHT]
#HEADLESS = true
#TIMEOUT = 30  # sec.
#TIME_TO_WAIT = 10  # sec.

#[MOBILE_PROXY]
#PROXY = ""
#CHANGE_IP_URL = ""

#[IMPORT]
#TWITTER_SEPARATOR = ":"
#DISCORD_SEPARATOR = ":"
#GOOGLE_SEPARATOR = ":"
#TWITTER_FIELDS = ["auth_token", "username", "password", "totp_secret"]
#DISCORD_FIELDS = ["auth_token"]
#GOOGLE_FIELDS = ["email", "password", "recovery_email", "totp_secret"]