[LOGGING]
LEVEL = "INFO"

[MINT]
DEFAULT_INVITE_CODE = "304799BB"

[TWITTER]
UNLOCK_ATTEMPTS = 5
USE_SUSPENDED_ACCOUNTS = false

[CAPTCHA]
CAPSOLVER_API_KEY = ""

[TRANSACTION]
WAIT_FOR_TX_RECEIPT = false